/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UsageRecord = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const UsageRecordArray = IDL.Vec(UsageRecord);
export const Plan = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canUseBackgroundRemover' : IDL.Func([IDL.Null], [IDL.Bool], ['query']),
  'getBackgroundRemoverUsage' : IDL.Func([IDL.Null], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLifetimeUsageCount' : IDL.Func([IDL.Null], [IDL.Nat], ['query']),
  'getRemainingUsage' : IDL.Func([IDL.Null], [IDL.Nat], ['query']),
  'getTopUsageRecordsQuery' : IDL.Func(
      [IDL.Nat],
      [UsageRecordArray],
      ['query'],
    ),
  'getUserPlan' : IDL.Func([IDL.Null], [Plan], ['query']),
  'incrementBackgroundRemoverUsage' : IDL.Func([IDL.Null], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'upgradeToPro' : IDL.Func([IDL.Null], [Plan], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UsageRecord = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const UsageRecordArray = IDL.Vec(UsageRecord);
  const Plan = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canUseBackgroundRemover' : IDL.Func([IDL.Null], [IDL.Bool], ['query']),
    'getBackgroundRemoverUsage' : IDL.Func([IDL.Null], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLifetimeUsageCount' : IDL.Func([IDL.Null], [IDL.Nat], ['query']),
    'getRemainingUsage' : IDL.Func([IDL.Null], [IDL.Nat], ['query']),
    'getTopUsageRecordsQuery' : IDL.Func(
        [IDL.Nat],
        [UsageRecordArray],
        ['query'],
      ),
    'getUserPlan' : IDL.Func([IDL.Null], [Plan], ['query']),
    'incrementBackgroundRemoverUsage' : IDL.Func([IDL.Null], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'upgradeToPro' : IDL.Func([IDL.Null], [Plan], []),
  });
};

export const init = ({ IDL }) => { return []; };