/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Plan = { 'pro' : null } |
  { 'free' : null };
export interface UsageRecord { 'date' : string, 'count' : bigint }
export type UsageRecordArray = Array<UsageRecord>;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canUseBackgroundRemover' : ActorMethod<[null], boolean>,
  'getBackgroundRemoverUsage' : ActorMethod<[null], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLifetimeUsageCount' : ActorMethod<[null], bigint>,
  'getRemainingUsage' : ActorMethod<[null], bigint>,
  'getTopUsageRecordsQuery' : ActorMethod<[bigint], UsageRecordArray>,
  'getUserPlan' : ActorMethod<[null], Plan>,
  'incrementBackgroundRemoverUsage' : ActorMethod<[null], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'upgradeToPro' : ActorMethod<[null], Plan>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];